### ISSUE TITLE
Main lobby picture frames invisible after /leave

### ISSUE THREAD

**Issue by SlimeDog** [MysticCity/MinigamesAPI#37]
My main lobby contain picture frames with items associated with the various games (for example, a minecart for FlyingCars). The following sequence causes some of the picture frames (and contents) to become invisible:
- Use Join sign or **/game join game** to go to a game lobby
- Use Leave sign or **/leave** to return to the main lobby

If I transport to a different world and back, the picture frames become visible. This behavior does not obtain if I simply **/tp** between the game lobby and the main lobby or for other (non-MG) games, so I think it is related to the MinigamesLib transport actions (but I do not understand why or how). Both MGFlyingCars and MGSnake exhibit this behavior.

Spigot 1.10 or 1.10.2, with the usual collection of up-to-date plugins: WE/WG, MV, PEX, etc. and Minigames build 29 (and since at least build 24, the first version I started testing).

**Comment by mepeisen** [comment]
Does F3+A (reloading chunks) after transport action fix it?

**Comment by SlimeDog** [comment]
Reloading chunks with **F3+A** does not render the frames visible.

The main lobby is 11x11 blocks, and contains 20 frames. Games return me to the center, so none of the frames is close enough to target. Only the six frames in the general direction I am looking when the game returns me to the main lobby are invisible; the other 14 to the sides and behind me are visible (of course, I have to turn to see those behind me, but at least two are in peripheral range.

**Comment by SlimeDog** [comment]
If debugging would benefit from observation on my test server, I would be happy to provide access.

**Comment by mepeisen** [comment]
I just verified the bug. It is really strange.

**Comment by mepeisen** [comment]
If I use the /warp command I ran into the same bug...

**Comment by mepeisen** [comment]
ok, I got the point. Item frames are entities and minigames lib removes antities at the end of the game.
The reason i Ran into the bug was that I used a butcher to remove all mobs before warping.
Will fix it.

**Comment by mepeisen** [comment]
Should be fixed. The newest snake Version uses a safe mob remove: only remove the sheeps/ wool blocks that were created by the Arena.
Please retry with latest snapshot build.

**Comment by SlimeDog** [comment]
Hmmm. The fix applied here seems to address a different issue. The bug I reported:

- does not involve removing item frames, just rendering them invisible; they are still present, and are visible if I change worlds and return

- involved both MGFlyingCars & MGSnake, so would appear to be a MinigamesLib issue

I note that MGSnake was updated in the latest snapshot, but MinigameLib was not. Please advise.

**Comment by SlimeDog** [comment]
Any more info? As I mentioned earlier in the thread: If debugging would benefit from observation on my test server, I would be happy to provide access.

**Comment by mepeisen** [comment]
Seems to be fixed. Check with latest snapshot (will be available in about 2 hours)
